using itpayroll.Areas.Identity.Data;
using itpayroll.Constant;
using itpayroll.Data;
using itpayroll.Models;
using itpayroll.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using itpayroll.Services;
using System.Text.Json;

namespace itpayroll.Controllers
{
    [Authorize(Roles = $"{Roles.SuperAdmin},{Roles.Admin},{Roles.HR}")]
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _configuration;
        private readonly AuditService _auditService;

        public EmployeeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IConfiguration configuration, AuditService auditService)
        {
            _context = context;
            _userManager = userManager;
            _configuration = configuration;
            _auditService = auditService;
        }

        private async Task PopulateShiftDropdown(int? selectedShiftId)
        {
            var shifts = await _context.Shifts
                .Where(s => s.IsActive)
                .Select(s => new { s.ShiftId, s.ShiftName })
                .ToListAsync();
            ViewBag.Shifts = new SelectList(shifts, "ShiftId", "ShiftName", selectedShiftId);
        }

        public IActionResult Index(string? searchString = null)
        {
            var employees = _context.Employees
                .Include(e => e.User)
                .Include(e => e.Shift)
                .Where(e => e.Status == EmploymentStatus.Active)
                .AsQueryable();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                employees = employees.Where(e =>
                    e.EmployeeNumber.Contains(searchString) ||
                    (e.User != null && (e.User.FirstName.Contains(searchString) || e.User.LastName.Contains(searchString))) ||
                    (e.Shift != null && e.Shift.ShiftName.Contains(searchString)));
            }

            ViewBag.CurrentFilter = searchString;
            var model = employees.ToList();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            await PopulateShiftDropdown(null);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel model)
        {
            // Remove auto-generated fields from ModelState (generated by controller, not user)
            ModelState.Remove(nameof(model.EmployeeNumber));
            ModelState.Remove(nameof(model.Email));

            // Generate auto-values FIRST
            if (string.IsNullOrEmpty(model.EmployeeNumber))
                model.EmployeeNumber = await GenerateEmployeeNumber();

            if (string.IsNullOrEmpty(model.Email))
            {
                var domain = _configuration["CompanySettings:Domain"] ?? "payflow.com";
                model.Email = await GenerateUniqueEmail(model.FirstName, model.LastName, domain);
            }

            if (!ModelState.IsValid)
            {
                await PopulateShiftDropdown(model.ShiftId);
                return View(model);
            }

            // 3. Create NEW ApplicationUser
            var user = new ApplicationUser
            {
                UserName = model.Email,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                CreatedBy = User.Identity?.Name ?? "System",
                CreatedDate = DateTime.UtcNow,
                IsActive = true,
                MustChangePassword = true,
                PasswordLastChanged = DateTime.UtcNow
            };

            // 4. Generate temp password
            var tempPassword = "Temp@" + Guid.NewGuid().ToString("N").Substring(0, 6);

            var result = await _userManager.CreateAsync(user, tempPassword);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
                await PopulateShiftDropdown(model.ShiftId);
                return View(model);
            }

            // 5. Add to Employee role
            await _userManager.AddToRoleAsync(user, Roles.Employee);

            // 6. Create Employee record
            var employee = new Employee
            {
                UserId = user.Id, // Link to NEW user
                EmployeeNumber = model.EmployeeNumber,
                Status = model.Status,
                BasicSalary = model.BasicSalary,
                HireDate = model.HireDate,
                TerminationDate = model.TerminationDate,
                ShiftId = model.ShiftId,
                Department = model.Department,
                Position = model.Position,
                EmploymentType = model.EmploymentType,
                SalaryType = model.SalaryType,
                PayFrequency = model.PayFrequency,
                BankName = model.BankName,
                BankAccountNumber = model.BankAccountNumber,
                TIN = model.TIN,
                SSSNumber = model.SSSNumber,
                PhilHealthNumber = model.PhilHealthNumber,
                PagIBIGNumber = model.PagIBIGNumber,
                CreatedBy = User.Identity?.Name ?? "System"
            };

            _context.Employees.Add(employee);
            await _context.SaveChangesAsync();

            // 7. Show credentials (ONE-TIME display)
            ViewBag.CreatedEmail = user.Email;
            ViewBag.TempPassword = tempPassword;
            return View("CreationSuccess", model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var employee = await _context.Employees
                .Include(e => e.User)
                .FirstOrDefaultAsync(e => e.EmployeeId == id);
            if (employee == null)
                return NotFound();

            var model = new EmployeeViewModel
            {
                EmployeeId = employee.EmployeeId,
                FirstName = employee.User?.FirstName ?? string.Empty,
                LastName = employee.User?.LastName ?? string.Empty,
                EmployeeNumber = employee.EmployeeNumber,
                Status = employee.Status,
                BasicSalary = employee.BasicSalary,
                HireDate = employee.HireDate,
                TerminationDate = employee.TerminationDate,
                ShiftId = employee.ShiftId,
                Department = employee.Department,
                Position = employee.Position,
                EmploymentType = employee.EmploymentType,
                SalaryType = employee.SalaryType,
                PayFrequency = employee.PayFrequency,
                BankName = employee.BankName,
                BankAccountNumber = employee.BankAccountNumber,
                TIN = employee.TIN,
                SSSNumber = employee.SSSNumber,
                PhilHealthNumber = employee.PhilHealthNumber,
                PagIBIGNumber = employee.PagIBIGNumber
            };

            await PopulateShiftDropdown(employee.ShiftId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                await PopulateShiftDropdown(model.ShiftId);
                return View(model);
            }

            var employee = await _context.Employees
                .Include(e => e.User)
                .FirstOrDefaultAsync(e => e.EmployeeId == model.EmployeeId);
            if (employee == null)
                return NotFound();

            var before = BuildEmployeeAuditSnapshot(employee);

            if (employee.User != null)
            {
                employee.User.FirstName = model.FirstName;
                employee.User.LastName = model.LastName;
                employee.User.ModifiedBy = User.Identity?.Name ?? "System";
                employee.User.ModifiedDate = DateTime.UtcNow;
            }

            employee.EmployeeNumber = model.EmployeeNumber;
            employee.Status = model.Status;
            employee.BasicSalary = model.BasicSalary;
            employee.HireDate = model.HireDate;
            employee.TerminationDate = model.TerminationDate;
            employee.ShiftId = model.ShiftId;
            employee.Department = model.Department;
            employee.Position = model.Position;
            employee.EmploymentType = model.EmploymentType;
            employee.SalaryType = model.SalaryType;
            employee.PayFrequency = model.PayFrequency;
            employee.BankName = model.BankName;
            employee.BankAccountNumber = model.BankAccountNumber;
            employee.TIN = model.TIN;
            employee.SSSNumber = model.SSSNumber;
            employee.PhilHealthNumber = model.PhilHealthNumber;
            employee.PagIBIGNumber = model.PagIBIGNumber;
            employee.ModifiedBy = User.Identity?.Name ?? "System";
            employee.ModifiedDate = DateTime.UtcNow;

            await _context.SaveChangesAsync();
            await _auditService.LogAsync(
                AuditAction.Update,
                $"Employee: {employee.EmployeeNumber}",
                LogType.System,
                "Employee",
                employee.EmployeeId.ToString(),
                BuildChangeMetadata(before, BuildEmployeeAuditSnapshot(employee)));

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var employee = await _context.Employees
                .Include(e => e.User)
                .Include(e => e.Shift)
                .FirstOrDefaultAsync(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            return View(employee);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var employee = await _context.Employees
                .Include(e => e.User)
                .FirstOrDefaultAsync(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            return View(employee);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees
                .Include(e => e.User)
                .FirstOrDefaultAsync(e => e.EmployeeId == id);

            if (employee == null)
                return NotFound();

            var before = BuildEmployeeAuditSnapshot(employee);
            employee.Status = EmploymentStatus.Inactive;
            employee.TerminationDate ??= DateTime.UtcNow.Date;
            employee.ModifiedBy = User.Identity?.Name ?? "System";
            employee.ModifiedDate = DateTime.UtcNow;

            if (employee.User != null)
            {
                employee.User.IsActive = false;
                employee.User.ModifiedBy = User.Identity?.Name ?? "System";
                employee.User.ModifiedDate = DateTime.UtcNow;
            }

            await _context.SaveChangesAsync();
            await _auditService.LogAsync(
                AuditAction.Delete,
                $"Employee: {employee.EmployeeNumber}",
                LogType.System,
                "Employee",
                employee.EmployeeId.ToString(),
                BuildChangeMetadata(before, BuildEmployeeAuditSnapshot(employee)));

            TempData["Success"] = "Employee deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        #region Helpers
        private static Dictionary<string, object?> BuildEmployeeAuditSnapshot(Employee employee)
        {
            return new Dictionary<string, object?>
            {
                ["FirstName"] = employee.User?.FirstName,
                ["LastName"] = employee.User?.LastName,
                ["EmployeeNumber"] = employee.EmployeeNumber,
                ["Status"] = employee.Status.ToString(),
                ["BasicSalary"] = employee.BasicSalary,
                ["HireDate"] = employee.HireDate.ToString("yyyy-MM-dd"),
                ["TerminationDate"] = employee.TerminationDate?.ToString("yyyy-MM-dd"),
                ["ShiftId"] = employee.ShiftId,
                ["Department"] = employee.Department,
                ["Position"] = employee.Position,
                ["EmploymentType"] = employee.EmploymentType?.ToString(),
                ["SalaryType"] = employee.SalaryType.ToString(),
                ["PayFrequency"] = employee.PayFrequency.ToString()
            };
        }

        private static string BuildChangeMetadata(Dictionary<string, object?> before, Dictionary<string, object?> after)
        {
            var changes = before
                .Where(item => !Equals(item.Value, after[item.Key]))
                .ToDictionary(item => item.Key, item => new { Before = item.Value, After = after[item.Key] });

            return JsonSerializer.Serialize(new { Before = before, After = after, Changes = changes });
        }

        private async Task<string> GenerateEmployeeNumber()
        {
            var lastEmployee = await _context.Employees
                .OrderByDescending(e => e.EmployeeId)
                .FirstOrDefaultAsync();

            int nextNumber = 1;
            if (lastEmployee != null && lastEmployee.EmployeeNumber.StartsWith("EMP-"))
            {
                var numberPart = lastEmployee.EmployeeNumber.Substring(4);
                if (int.TryParse(numberPart, out int lastNum))
                    nextNumber = lastNum + 1;
            }
            return $"EMP-{nextNumber:D4}";
        }

        private async Task<string> GenerateUniqueEmail(string firstName, string lastName, string domain)
        {
            var baseEmail = $"{firstName.ToLower().Trim()}.{lastName.ToLower().Trim()}@{domain}";
            var email = baseEmail;
            int counter = 0;

            while (await _userManager.FindByEmailAsync(email) != null)
            {
                counter++;
                email = $"{firstName.ToLower().Trim()}{counter}@{domain}";
            }
            return email;
        }
        #endregion
    }
}
